#!/bin/bash

set -e

restore_configs

export V1_VERSION=${V1_VERSION}S

$CFGDIR/common/v1-base-config
$CFGDIR/common/cnc-config
$CFGDIR/boards/ramps
$CFGDIR/accessories/reprap_discount_full_graphic_lcd
$CFGDIR/accessories/no-dual-endstops
$CFGDIR/accessories/laser

opt_set X_DRIVER_TYPE "A4988"
opt_set Y_DRIVER_TYPE "A4988"
opt_set Z_DRIVER_TYPE "A4988"
# y 193-40=153 but should be 150
opt_set DEFAULT_AXIS_STEPS_PER_UNIT "{ 100, 100, 393, 100 }"
opt_set DEFAULT_MAX_FEEDRATE "{ 110, 110, 70, 25 }"
opt_set DEFAULT_MAX_ACCELERATION "{ 400, 400, 150, 180 }"
opt_set DEFAULT_ACCELERATION          "400"    
opt_set DEFAULT_RETRACT_ACCELERATION  "400"    # Für Rückzüge (beim Fräsen weniger relevant)
opt_set DEFAULT_TRAVEL_ACCELERATION   "400"    # Für Leerfahrten (G0)

# NB! The values below will only have any effect if the board is fitted with programmable drivers
opt_set X_MICROSTEPS "16"
opt_set Y_MICROSTEPS "16"
opt_set Z_MICROSTEPS "16"
opt_set X_BED_SIZE "500"
opt_set Y_BED_SIZE "500"
opt_set SPINDLE_LASER_PWM_PIN "8"

opt_enable \
    PSU_CONTROL
opt_set PSU_DEFAULT_OFF true
opt_set PSU_CONTROL_PIN "12"

export PLATFORMIO_ENV=mega2560
