#!/bin/bash

set -e

restore_configs

export V1_VERSION=${V1_VERSION}S

$CFGDIR/common/v1-base-config
$CFGDIR/common/cnc-config
$CFGDIR/boards/ramps
$CFGDIR/accessories/reprap_discount_full_graphic_lcd
$CFGDIR/accessories/no-dual-endstops
$CFGDIR/accessories/laser

opt_set X_DRIVER_TYPE "A4988"
opt_set Y_DRIVER_TYPE "A4988"
opt_set Z_DRIVER_TYPE "A4988"
# y 193-40=153 but should be 150
opt_set DEFAULT_AXIS_STEPS_PER_UNIT "{ 100, 100, 393, 100 }"
opt_set DEFAULT_MAX_FEEDRATE "{ 110, 110, 50, 25 }"
opt_set HOMING_FEEDRATE_MM_M "{ (50*60), (50*60), (30*60) }"
opt_set DEFAULT_MAX_ACCELERATION "{ 400, 400, 150, 180 }"
opt_set DEFAULT_ACCELERATION          "400"    
opt_set DEFAULT_RETRACT_ACCELERATION  "400"    # Für Rückzüge (beim Fräsen weniger relevant)
opt_set DEFAULT_TRAVEL_ACCELERATION   "400"    # Für Leerfahrten (G0)

# NB! The values below will only have any effect if the board is fitted with programmable drivers
opt_set X_MICROSTEPS "16"
opt_set Y_MICROSTEPS "16"
opt_set Z_MICROSTEPS "16"
opt_set X_BED_SIZE "380"
opt_set Y_BED_SIZE "380"
opt_set Z_MAX_POS "0"       # Der höchste Punkt ist 0
opt_set Z_MIN_POS "-150"    # Der Tisch liegt bei -150 (an deine Maschine anpassen!)
opt_set  Z_CLEARANCE_FOR_HOMING "0"

opt_set ENCODER_PULSES_PER_STEP 4
opt_set ENCODER_STEPS_PER_MENU_ITEM 1

opt_enable \
    PSU_CONTROL\
    ENDSTOPPULLUP_ZMAX \
    ENDSTOP_INTERRUPTS_FEATURE \
    QUICK_HOME \
    REVERSE_ENCODER_DIRECTION \
    MIN_SOFTWARE_ENDSTOPS \
    MIN_SOFTWARE_ENDSTOP_X \
    MIN_SOFTWARE_ENDSTOP_Y \
    MIN_SOFTWARE_ENDSTOP_Z \
    MAX_SOFTWARE_ENDSTOPS \
    MAX_SOFTWARE_ENDSTOP_X \
    MAX_SOFTWARE_ENDSTOP_Y \
    MAX_SOFTWARE_ENDSTOP_Z

opt_set PSU_DEFAULT_OFF true
opt_set PSU_CONTROL_PIN "12"

opt_set SPINDLE_LASER_PWM_PIN "8"
opt_set X_MIN_ENDSTOP_HIT_STATE "LOW"
opt_set Y_MIN_ENDSTOP_HIT_STATE "LOW"
opt_set Z_MAX_ENDSTOP_HIT_STATE "LOW"
opt_set Z_HOME_DIR 1 # Z home to max endstop
opt_set Z_MIN_PIN "-1"
opt_set HOME_AXIS_ORDER Z XY # Home Z first to get it out of the way, then X and Y together to save time

opt_set ST7920_DELAY_1 "DELAY_NS(400)"
opt_set ST7920_DELAY_2 "DELAY_NS(400)"
opt_set ST7920_DELAY_3 "DELAY_NS(400)"

export PLATFORMIO_ENV=mega2560
